title: BreakerxFixer
description: Writeups de hacking

collections:
  writeups:
    output: true
    permalink: /writeups/:path/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
