title: BreakerxFixer
description: Writeups de hacking

future: true

collections:
  writeups:
    output: true
    permalink: /writeups/:name/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
