import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

def replace_in_file(rel_path, replacements):
    path = os.path.join(BASE_DIR, rel_path)
    if not os.path.exists(path):
        print(f"Skipping {rel_path}, not found.")
        return
    
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original_len = len(content)
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
        else:
            print(f"Warning: Could not find target text in {rel_path}: {old[:50]}...")
            
    if len(content) != original_len:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated {rel_path}")
    else:
        print(f"No changes made to {rel_path}")

# --- ABOUT US ---
about_us_reps = [
    ('SCROLL DOWN', '<span data-en="SCROLL DOWN" data-es="BAJAR">SCROLL DOWN</span>'),
    ('<p>\n                We are BreakerxFixer', '<p data-en="We are BreakerxFixer, a small team focused on both offensive and defensive security, CTF challenges, and hands-on vulnerability research. <br><br>Our work revolves around breaking systems, hardening them, understanding how they fail, protecting them, and documenting the process through detailed writeups and Proofs of Concept.<br><br>We take a practical approach to cybersecurity — no empty theory, no recycled content — everything we share is built, tested, and understood from the ground up.<br><br>From exploiting vulnerabilities to analyzing defensive mechanisms, our goal is to cover the full attack surface and develop a deeper understanding of real-world security scenarios.<br><br>We are constantly learning, building, and refining our skills, aiming to contribute meaningful insights to the community while evolving as security researchers." data-es="Somos BreakerxFixer, un pequeño equipo centrado tanto en seguridad ofensiva como defensiva, desafíos CTF e investigación de vulnerabilidades práctica. <br><br>Nuestro trabajo gira en torno a romper sistemas, fortalecerlos, comprender cómo fallan, protegerlos y documentar el proceso a través de writeups detallados y Pruebas de Concepto.<br><br>Adoptamos un enfoque práctico de la ciberseguridad: nada de teoría vacía, nada de contenido reciclado; todo lo que compartimos se construye, se prueba y se comprende desde cero.<br><br>Desde la explotación de vulnerabilidades hasta el análisis de mecanismos defensivos, nuestro objetivo es cubrir toda la superficie de ataque y desarrollar una comprensión más profunda de los escenarios de seguridad del mundo real.<br><br>Estamos en constante aprendizaje, construcción y refinamiento de nuestras habilidades, con el objetivo de aportar ideas significativas a la comunidad mientras evolucionamos como investigadores de seguridad.">\n                Somos BreakerxFixer, un pequeño equipo centrado tanto en seguridad ofensiva como defensiva, desafíos CTF e investigación de vulnerabilidades práctica.'),
    ('<h2 class="member-title">Kyrox</h2>\n            <p>\n                I’m Kyrox', '<h2 class="member-title">Kyrox</h2>\n            <p data-en="I’m Kyrox, a cybersecurity enthusiast who started exploring hacking in 2024 through online content, initially experimenting with Wi-Fi security and basic attack techniques. What began as curiosity quickly turned into a clear career path.<br><br>During my studies, I developed a strong foundation in Linux, while also learning multiple programming languages including Python, Bash, Java, and Rust. These skills allowed me to better understand how systems work — and how they can be broken.<br><br>While completing an internship, I built a fully functional website from scratch using HTML, CSS, and JavaScript. That project became my first real testing ground for security, where I identified and explored several vulnerabilities, reinforcing my interest in web security.<br><br>I am currently pursuing a higher degree in Systems Administration (ASIR), where I’ve focused heavily on cybersecurity — especially offensive security and web hacking, which I’m most passionate about.<br><br>I consistently challenge myself by solving Hack The Box exercises on a daily basis and working towards certifications to validate and expand my knowledge.<br><br>My goal is to continuously improve, break systems to understand them, and evolve into a skilled security professional." data-es="Soy Kyrox, un entusiasta de la ciberseguridad que comenzó a explorar el hacking en 2024 a través de contenido online, experimentando inicialmente con la seguridad Wi-Fi y técnicas de ataque básicas. Lo que comenzó como curiosidad se convirtió rápidamente en una trayectoria profesional clara.<br><br>Durante mis estudios, desarrollé una base sólida en Linux, mientras también aprendía múltiples lenguajes de programación, incluyendo Python, Bash, Java y Rust. Estas habilidades me permitieron comprender mejor cómo funcionan los sistemas y cómo se pueden romper.<br><br>Mientras realizaba unas prácticas, construí un sitio web totalmente funcional desde cero utilizando HTML, CSS y JavaScript. Ese proyecto se convirtió en mi primer campo de pruebas real para la seguridad, donde identifiqué y exploré varias vulnerabilidades, reforzando mi interés en la seguridad web.<br><br>Actualmente estoy cursando un grado superior en Administración de Sistemas (ASIR), donde me he centrado intensamente en la ciberseguridad, especialmente en el hacking ético y web, que es lo que más me apasiona.<br><br>Me reto constantemente resolviendo ejercicios de Hack The Box a diario y trabajando para obtener certificaciones que validen y amplíen mis conocimientos.<br><br>Mi objetivo es mejorar continuamente, romper sistemas para entenderlos y evolucionar como un profesional de la seguridad cualificado.">\n                Soy Kyrox, un entusiasta de la ciberseguridad que comenzó a explorar el hacking en 2024 a través de contenido online.'),
    ('<h2 class="member-title">Winter</h2>\n            <p>\n                I’m 0xWinter', '<h2 class="member-title">Winter</h2>\n            <p data-en="I’m 0xWinter, a freelance systems administrator with over 6 years of experience and a former sound technician — a background that shaped my attention to detail, precision, and problem-solving mindset.<br><br>I started working as an IT emergency technician, providing rapid-response support and repair services for small and medium-sized businesses, as well as hardware and mobile device repairs for individual clients. This hands-on experience built a strong technical foundation and the ability to operate under pressure.<br><br>Over time, my focus shifted towards cybersecurity through CTF competitions and structured learning. After achieving a 97% score in the eJPT certification, I transitioned into a defensive security path, specializing in blue team operations, digital forensics, and OSINT.<br><br>I have participated in countless CTF challenges, reaching the #1 position in Spain on TryHackMe for several consecutive months, demonstrating both consistency and depth in practical skills.<br><br>Additionally, I obtained the Google Certificate in Defensive Cybersecurity, further strengthening my expertise in threat detection, analysis, and response.<br><br>My approach is simple: understand systems deeply, identify their weaknesses, and use that knowledge to defend and improve them." data-es="Soy 0xWinter, administrador de sistemas freelance con más de 6 años de experiencia y extécnico de sonido, una formación que forjó mi atención al detalle, precisión y mentalidad de resolución de problemas.<br><br>Comencé a trabajar como técnico de emergencias IT, brindando soporte de respuesta rápida y servicios de reparación para pequeñas y medianas empresas, así como reparaciones de hardware y dispositivos móviles para clientes individuales. Esta experiencia práctica construyó una base técnica sólida y la capacidad de operar bajo presión.<br><br>Con el tiempo, mi enfoque se desplazó hacia la ciberseguridad a través de competiciones CTF y aprendizaje estructurado. Tras lograr una puntuación del 97% en la certificación eJPT, hice la transición a una trayectoria de seguridad defensiva, especializándome en operaciones de blue team, forense digital y OSINT.<br><br>He participado en innumerables desafíos CTF, alcanzando la posición #1 en España en TryHackMe durante varios meses consecutivos, demostrando tanto consistencia como profundidad en habilidades prácticas.<br><br>Además, obtuve el Certificado de Google en Ciberseguridad Defensiva, fortaleciendo aún más mi experiencia en detección, análisis y respuesta ante amenazas.<br><br>Mi enfoque es simple: entender los sistemas profundamente, identificar sus debilidades y usar ese conocimiento para defenderlos y mejorarlos.">\n                Soy 0xWinter, administrador de sistemas freelance con más de 6 años de experiencia y extécnico de sonido.'),
]

# --- WRITEUPS ---
writeups_reps = [
    ('<h1>🧠 Writeups</h1>', '<h1 data-en="🧠 Writeups" data-es="🧠 Writeups">🧠 Writeups</h1>'),
    ('placeholder="Buscar por máquina, tags, dificultad, plataforma..."', 'placeholder="Buscar por máquina, tags, dificultad, plataforma..." data-es-placeholder="Buscar por máquina, tags, dificultad, plataforma..." data-en-placeholder="Search by machine, tags, difficulty, platform..."'),
]

# --- CTF ---
ctf_reps = [
    ('Mission 03: The Impostor</div>\n                    <div class="mission-details">"The firewall', 'Mission 03: The Impostor</div>\n                    <div class="mission-details" data-en=\'"The firewall only trusts its own kind. Forge your header, become the AdminBrowser."\' data-es=\'"El firewall solo confía en los de su clase. Falsifica tu cabecera, conviértete en AdminBrowser."\'>"The firewall'),
    ('Mission 04: Unstoppable Force</div>\n                    <div class="mission-details">"Three strikes', 'Mission 04: Unstoppable Force</div>\n                    <div class="mission-details" data-en=\'"Three strikes and you\\\'re out. Unless you make them believe you are attacking from inside the house."\' data-es=\'"A la tercera va la vencida. A menos que les hagas creer que estás atacando desde dentro de la casa."\'>"Three strikes'),
    ('Mission 05: Logic Fallacy</div>\n                    <div class="mission-details">"Tautology', 'Mission 05: Logic Fallacy</div>\n                    <div class="mission-details" data-en=\'"Tautology is the death of poorly coded authentication. Make the database agree with you."\' data-es=\'"La tautología es la muerte de una autenticación mal programada. Haz que la base de datos esté de acuerdo contigo."\'>"Tautology'),
    ('Mission 06: The Wanderer</div>\n                    <div class="mission-details">"Files', 'Mission 06: The Wanderer</div>\n                    <div class="mission-details" data-en=\'"Files are meant to stay in their directories. Traverse the path and find the core secrets."\' data-es=\'"Los archivos deben permanecer en sus directorios. Atraviesa la ruta y encuentra los secretos centrales."\'>"Files'),
    ('Mission 07: Phantom Ping</div>\n                    <div class="mission-details">"A simple', 'Mission 07: Phantom Ping</div>\n                    <div class="mission-details" data-en=\'"A simple network test... or a gateway to execute lethal commands in the pipeline."\' data-es=\'"Una simple prueba de red... o una puerta de enlace para ejecutar comandos letales en la tubería."\'>"A simple'),
    ('Mission 08: Shattered Trust</div>\n                    <div class="mission-details">"A guest', 'Mission 08: Shattered Trust</div>\n                    <div class="mission-details" data-en=\'"A guest token signed with a weak promise. Crack the secret, forge the admin token."\' data-es=\'"Un token de invitado firmado con una promesa débil. Descifra el secreto, falsifica el token de administrador."\'>"A guest'),
    ('Mission 09: Careless Whispers</div>\n                    <div class="mission-details">"When the', 'Mission 09: Careless Whispers</div>\n                    <div class="mission-details" data-en=\'"When the server panics, it talks too much. Force a forbidden method, listen to the headers."\' data-es=\'"Cuando el servidor entra en pánico, habla demasiado. Fuerza un método prohibido, escucha las cabeceras."\'>"When the'),
    ('Mission 10: NoSQL Nightmare</div>\n                    <div class="mission-details">"Why guess', 'Mission 10: NoSQL Nightmare</div>\n                    <div class="mission-details" data-en=\'"Why guess the password when you can just ask if it\\\'s \\\'not equal to nothing\\\'?"\' data-es=\'"¿Por qué adivinar la contraseña cuando puedes simplemente preguntar si \\\'no es igual a nada\\\'?"\'>"Why guess'),
]

if __name__ == "__main__":
    replace_in_file('aboutus.html', about_us_reps)
    replace_in_file('writeups.html', writeups_reps)
    replace_in_file('ctf.html', ctf_reps)
